[-c8]
func_addr = 4195766
name = "conn_array"
stack_offset = -200
stack_offset_type = 1
size = 1
type = "unsigned char"

[-10]
func_addr = 4195766
name = "conn_canary"
stack_offset = -16
stack_offset_type = 1
size = 8
type = "unsigned long long"
